name: spedread
base: core24
adopt-info: spedread
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  armhf:
  arm64:

slots:
  spedread:
    interface: dbus
    bus: session
    name: com.github.Darazaki.Spedread

apps:
  spedread:
    command: usr/bin/spedread
    extensions: [gnome]
    common-id: com.github.Darazaki.Spedread
    desktop: usr/share/applications/com.github.Darazaki.Spedread.desktop

parts:
  spedread:
    source: .
    plugin: meson
    parse-info: [usr/share/appdata/com.github.Darazaki.Spedread.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    override-pull: |
      craftctl default
      sed -e 's|Icon=com.github.Darazaki.Spedread|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.Darazaki.Spedread.svg|' -i data/com.github.Darazaki.Spedread.desktop.in
