name: Build & Test

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build-n-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install meson build-essential valac libadwaita-1-dev appstream-util desktop-file-utils
    - name: configure
      run: meson setup build
    - name: build
      run: ninja -C build
    - name: test
      run: ninja -C build test
