name: Build & Test

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build-n-test:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: sudo apt-get install meson build-essential valac libadwaita-1-dev appstream-util desktop-file-utils gettext
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build
    - name: Test
      run: ninja -C build test

  flatpak-build:

    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    steps:
    - uses: actions/checkout@v6
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Spedread.flatpak
        manifest-path: com.github.Darazaki.Spedread.json

  snap-build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - uses: snapcore/action-build@v1
      id: build
    - name: Install built snap package
      run: sudo snap install --dangerous ${{ steps.build.outputs.snap }}
    - name: Verify that the installed snap package runs
      run: spedread --help
    - uses: actions/upload-artifact@v4
      with:
        name: Spedread-x86_64.snap
        path: ${{ steps.build.outputs.snap }}
