name: Build & Test

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build-n-test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install meson build-essential valac libadwaita-1-dev appstream-util desktop-file-utils gettext
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build
    - name: Test
      run: ninja -C build test
